---
- name: geerlingguy.php
  version: "4.3.1"
- name: nginxinc.nginx
  version: "0.14.0"
- name: geerlingguy.mysql
  version: "3.1.0"
- name: manala.beanstalkd
  version: "2.0.1"
- name: geerlingguy.redis
  version: "1.6.0"
- name: geerlingguy.php-redis
  version: "3.2.1"
- name: geerlingguy.pip
  version: "1.3.0"
