---
- hosts: targets
  become: true
  vars_files:
    - vars/main.yaml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
    - name: Install libgmp3-dev, sqlite3
      apt:
        name:
          - libgmp3-dev
          - sqlite3
          - libsqlite3-dev
          - libonig-dev  # For mbstring
          - libzip-dev  # For zip extension
          - unzip  # For faster unzipping with composer
        state: present
    - import_role:
        name: geerlingguy.php
    - name: Place php.ini
      template:
        src: templates/php.ini
        dest: /usr/local/lib/php.ini
    - import_role:
        name: geerlingguy.composer
