---
- name: Nginx
  hosts: targets
  roles:
    - role: nginxinc.nginx
  vars:
    nginx_debug_output: true
    nginx_branch: stable
  tasks:
    - name: Create /var/www/html directory
      file:
        path: /var/www/html
        state: directory
        owner: root
        group: root

    - name: Delete default.conf.off
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Copy site.conf
      template:
        src: templates/http/site.conf.j2
        dest: /etc/nginx/conf.d/site.conf
